<?php
/**
 * The template for displaying single Glossary Terms
 *
 * @link https://developer.wordpress.org/themes/basics/template-hierarchy/#single-post
 *
 * @package neubird
 */

get_header();

// Get glossary meta
$definition = get_field('definition');
$short_description = get_field('short_description');

// Enqueue FAQ block styles for glossary posts
wp_enqueue_style('faq-block-style', get_template_directory_uri() . '/css/faq-block.css', array(), '1.0.0');
?>

<main id="primary" class="site-main">

    <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
        <section class="glossary-single-content">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <?php neubird_breadcrumbs(); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-8">
                        <div class="glossary-content-area">
                            <div class="glossary-header">
                                <h1 class="glossary-term-title"><?php the_title(); ?></h1>
                                <?php if ($short_description) : ?>
                                    <div class="glossary-short-description">
                                        <p class="lead"><?php echo esc_html($short_description); ?></p>
                                    </div>
                                <?php endif; ?>
                            </div>
                            
                            <?php if ($definition) : ?>
                                <div class="glossary-definition">
                                    <h2>Definition</h2>
                                    <div class="definition-content">
                                        <?php echo wp_kses_post($definition); ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                            
                            <div class="glossary-main-content">
                                <?php 
                                $glossary_content = get_field('glossary_content');
                                if ($glossary_content) {
                                    echo wp_kses_post($glossary_content);
                                } else {
                                    // Fallback to default content if ACF field is empty
                                    the_content();
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <?php
                        // Table of Contents functionality
                        $toc_enable = get_field('toc_enable');
                        $toc_title = get_field('toc_title') ?: 'Table of Contents';
                        $toc_enable_numbering = get_field('toc_enable_numbering');
                        $toc_sticky_position = get_field('toc_sticky_position');
                        
                        if ($toc_enable) :
                        ?>
                        <div class="table-of-contents-wrapper <?php echo $toc_sticky_position ? 'sticky-toc' : ''; ?>">
                            <div class="table-of-contents">
                                <h3 class="toc-title"><?php echo esc_html($toc_title); ?></h3>
                                <ul class="toc-list <?php echo $toc_enable_numbering ? 'numbered' : ''; ?>" id="toc-list">
                                    <!-- TOC items will be generated by JavaScript -->
                                </ul>
                            </div>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </section>

        <?php 
        // FAQ Section for Glossary (similar to Integration page)
        $glossary_faq_header = get_field('glossary_faq_header');
        $glossary_faq_subheading = get_field('glossary_faq_subheading');
        $glossary_faq_display_style = get_field('glossary_faq_display_style');
        $glossary_faq_layout = get_field('glossary_faq_layout');
        $glossary_faq_enable_schema = get_field('glossary_faq_enable_schema');
        $glossary_faq_items = get_field('glossary_faq_items');

        if ($glossary_faq_items && !empty($glossary_faq_items)) :
        ?>
        <section class="glossary-faq-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="glossary-faq-content">
                            <?php if ($glossary_faq_header) : ?>
                                <h2 class="faq-header"><?php echo esc_html($glossary_faq_header); ?></h2>
                            <?php endif; ?>
                            
                            <?php if ($glossary_faq_subheading) : ?>
                                <p class="faq-subheading glossary-help"><?php echo esc_html($glossary_faq_subheading); ?></p>
                            <?php endif; ?>
                            
                            <div class="faq-container <?php echo esc_attr($glossary_faq_layout ?: 'single_column'); ?>">
                                <?php foreach ($glossary_faq_items as $index => $faq_item) : 
                                    $question = $faq_item['question'];
                                    $answer = $faq_item['answer'];
                                    $is_first = $index === 0;
                                    
                                    // Determine if this FAQ should be expanded based on display style
                                    $is_expanded = false;
                                    switch ($glossary_faq_display_style) {
                                        case 'accordion_open':
                                            $is_expanded = true;
                                            break;
                                        case 'first_open':
                                            $is_expanded = $is_first;
                                            break;
                                        case 'accordion_closed':
                                            $is_expanded = false;
                                            break;
                                        case 'static':
                                        case 'always_open':
                                            $is_expanded = true;
                                            break;
                                        case 'accordion':
                                        default:
                                            $is_expanded = $is_first; // Default behavior - first expanded
                                            break;
                                    }
                                    
                                    $has_toggle = ($glossary_faq_display_style !== 'static' && $glossary_faq_display_style !== 'always_open');
                                ?>
                                    <div class="faq-item <?php echo $is_expanded ? 'active' : ''; ?>">
                                        <?php if (!$has_toggle) : ?>
                                            <div class="faq-question-static">
                                                <h4><?php echo esc_html($question); ?></h4>
                                            </div>
                                            <div class="faq-answer-static">
                                                <div class="faq-answer-content">
                                                    <?php echo wp_kses_post($answer); ?>
                                                </div>
                                            </div>
                                        <?php else : ?>
                                            <button class="faq-question" 
                                                    aria-expanded="<?php echo $is_expanded ? 'true' : 'false'; ?>"
                                                    data-toggle="faq-answer-<?php echo $index; ?>">
                                                <h4><?php echo esc_html($question); ?></h4>
                                                <span class="faq-toggle-icon" aria-hidden="true">
                                                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                        <line class="horizontal-line" x1="4" y1="8" x2="12" y2="8" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                                                        <line class="vertical-line" x1="8" y1="4" x2="8" y2="12" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                                                    </svg>
                                                </span>
                                            </button>
                                            <div class="faq-answer <?php echo $is_expanded ? 'active' : ''; ?>" id="faq-answer-<?php echo $index; ?>" <?php echo !$is_expanded ? 'style="display: none;"' : ''; ?>>
                                                <div class="faq-answer-content">
                                                    <?php echo wp_kses_post($answer); ?>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <?php if ($glossary_faq_enable_schema && $glossary_faq_items) : ?>
        <?php
            $schema = [
                '@context' => 'https://schema.org',
                '@type' => 'FAQPage',
                'mainEntity' => []
            ];
            foreach ($glossary_faq_items as $faq_item) {
                $q = wp_strip_all_tags($faq_item['question']);
                $a = wp_strip_all_tags($faq_item['answer']);
                $a = preg_replace('/\s+/', ' ', $a);
                $a = trim($a);
                if (!$q || !$a) { continue; }
                $schema['mainEntity'][] = [
                    '@type' => 'Question',
                    'name' => $q,
                    'acceptedAnswer' => [
                        '@type' => 'Answer',
                        'text' => $a,
                    ],
                ];
            }
        ?>
        <script type="application/ld+json">
        <?php echo wp_json_encode($schema, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); ?>
        </script>
        <?php endif; ?>
        <?php endif; ?>

        <?php
        // Auto-generate schema markup for glossary terms
        $definition = get_field('definition');
        $short_description = get_field('short_description');
        
        if ($definition || $short_description) :
            $desc = $short_description ?: wp_strip_all_tags($definition);
            $desc = preg_replace('/\s+/', ' ', $desc);
            $desc = trim($desc);
            $defined = [
                '@context' => 'https://schema.org',
                '@type' => 'DefinedTerm',
                'name' => get_the_title(),
                'description' => $desc,
                'url' => get_permalink(),
                'inDefinedTermSet' => [
                    '@type' => 'DefinedTermSet',
                    '@id' => get_post_type_archive_link('glossary'),
                    'name' => 'Glossary',
                    'description' => 'A comprehensive glossary of terms and definitions',
                ],
            ];
            if ($definition && $short_description) {
                $defClean = wp_strip_all_tags($definition);
                $defClean = preg_replace('/\s+/', ' ', $defClean);
                $defClean = trim($defClean);
                $defined['definition'] = $defClean;
            }
        ?>
        <script type="application/ld+json">
        <?php echo wp_json_encode($defined, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); ?>
        </script>
        <?php endif; ?>

        <section class="glossary-navigation">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="post-navigation">
                            <?php
                            $prev_post = get_previous_post();
                            $next_post = get_next_post();
                            ?>
                            
                            <?php if (!empty($prev_post)) : ?>
                                <div class="nav-previous">
                                    <a href="<?php echo esc_url(get_permalink($prev_post->ID)); ?>">
                                        <span class="nav-subtitle">&larr; Previous Term</span>
                                        <span class="nav-title"><?php echo esc_html(get_the_title($prev_post->ID)); ?></span>
                                    </a>
                                </div>
                            <?php endif; ?>
                            
                            <?php if (!empty($next_post)) : ?>
                                <div class="nav-next">
                                    <a href="<?php echo esc_url(get_permalink($next_post->ID)); ?>">
                                        <span class="nav-subtitle">Next Term &rarr;</span>
                                        <span class="nav-title"><?php echo esc_html(get_the_title($next_post->ID)); ?></span>
                                    </a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <?php
        // Get related glossary terms (alphabetically adjacent)
        $current_letter = strtoupper(substr(get_the_title(), 0, 1));
        $related_args = array(
            'post_type' => 'glossary',
            'posts_per_page' => 6,
            'post__not_in' => array(get_the_ID()),
            'orderby' => 'title',
            'order' => 'ASC',
            'meta_query' => array(
                array(
                    'key' => '_letter_filter',
                    'value' => $current_letter,
                    'compare' => 'LIKE'
                )
            )
        );
        
        // If no posts with the letter filter, fall back to a broader search
        $related_terms = new WP_Query($related_args);
        
        if (!$related_terms->have_posts()) {
            $related_args = array(
                'post_type' => 'glossary',
                'posts_per_page' => 6,
                'post__not_in' => array(get_the_ID()),
                'orderby' => 'title',
                'order' => 'ASC'
            );
            $related_terms = new WP_Query($related_args);
        }
        
        if ($related_terms->have_posts()) :
        ?>
        <section class="related-glossary-terms">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h3>Related Terms</h3>
                        <div class="related-terms-grid">
                            <?php while ($related_terms->have_posts()) : $related_terms->the_post(); 
                                $rel_short_desc = get_field('short_description', get_the_ID());
                            ?>
                                <div class="related-term-item">
                                    <h4><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h4>
                                    <?php if ($rel_short_desc) : ?>
                                        <p><?php echo esc_html(wp_trim_words($rel_short_desc, 15)); ?></p>
                                    <?php endif; ?>
                                </div>
                            <?php endwhile; ?>
                        </div>
                        <div class="view-all-terms">
                            <a href="<?php echo esc_url(get_post_type_archive_link('glossary')); ?>" class="btn btn-outline-primary">View All Terms</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <?php 
        wp_reset_postdata();
        endif; 
        ?>
    </article><!-- #post-<?php the_ID(); ?> -->

</main><!-- #main -->

<?php
// Enqueue table of contents CSS if TOC is enabled
$toc_enable = get_field('toc_enable');
if ($toc_enable) {
    wp_enqueue_style('table-of-contents-style', get_template_directory_uri() . '/css/table-of-contents.css', array(), '1.0.0');
}
?>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Table of Contents Generation
    const tocEnable = <?php echo $toc_enable ? 'true' : 'false'; ?>;
    
    if (tocEnable) {
        const tocList = document.getElementById('toc-list');
        const contentArea = document.querySelector('.glossary-main-content');
        
        if (tocList && contentArea) {
            const headings = contentArea.querySelectorAll('h2, h3, h4, h5, h6');
            
            if (headings.length > 0) {
                headings.forEach(function(heading, index) {
                    // Create unique ID for heading if it doesn't have one
                    if (!heading.id) {
                        const headingText = heading.textContent.trim();
                        const headingId = 'heading-' + headingText.toLowerCase()
                            .replace(/[^\w\s-]/g, '')
                            .replace(/\s+/g, '-')
                            .replace(/-+/g, '-')
                            .replace(/^-|-$/g, '') + '-' + index;
                        heading.id = headingId;
                    }
                    
                    // Create TOC item
                    const tocItem = document.createElement('li');
                    const level = parseInt(heading.tagName.charAt(1));
                    tocItem.className = 'toc-item level-' + level;
                    
                    const tocLink = document.createElement('a');
                    tocLink.href = '#' + heading.id;
                    tocLink.className = 'toc-link';
                    tocLink.textContent = heading.textContent.trim();
                    
                    // Smooth scroll to heading
                    tocLink.addEventListener('click', function(e) {
                        e.preventDefault();
                        const targetHeading = document.getElementById(heading.id);
                        if (targetHeading) {
                            targetHeading.scrollIntoView({
                                behavior: 'smooth',
                                block: 'start'
                            });
                            
                            // Update active state
                            document.querySelectorAll('.toc-link').forEach(link => {
                                link.classList.remove('active');
                            });
                            tocLink.classList.add('active');
                        }
                    });
                    
                    tocItem.appendChild(tocLink);
                    tocList.appendChild(tocItem);
                });
                
                // Highlight current section on scroll
                let ticking = false;
                
                function updateActiveLink() {
                    const scrollPosition = window.scrollY + 100;
                    let activeHeading = null;
                    
                    headings.forEach(function(heading) {
                        const headingTop = heading.offsetTop;
                        if (scrollPosition >= headingTop) {
                            activeHeading = heading;
                        }
                    });
                    
                    // Update active states
                    document.querySelectorAll('.toc-link').forEach(link => {
                        link.classList.remove('active');
                    });
                    
                    if (activeHeading) {
                        const activeLink = document.querySelector('.toc-link[href="#' + activeHeading.id + '"]');
                        if (activeLink) {
                            activeLink.classList.add('active');
                        }
                    }
                    
                    ticking = false;
                }
                
                window.addEventListener('scroll', function() {
                    if (!ticking) {
                        requestAnimationFrame(updateActiveLink);
                        ticking = true;
                    }
                });
                
                // Initial active state
                updateActiveLink();
            } else {
                // Hide TOC if no headings found
                const tocWrapper = document.querySelector('.table-of-contents-wrapper');
                if (tocWrapper) {
                    tocWrapper.style.display = 'none';
                }
            }
        }
    }
    
    // Glossary FAQ Toggle Functionality
    const glossaryFaqToggles = document.querySelectorAll('.glossary-faq-section .faq-question[data-toggle]');
    
    glossaryFaqToggles.forEach(function(toggle) {
        toggle.addEventListener('click', function(e) {
            e.preventDefault();
            
            const faqItem = this.closest('.faq-item');
            const targetId = this.getAttribute('data-toggle');
            const targetAnswer = document.getElementById(targetId);
            
            if (targetAnswer) {
                if (faqItem.classList.contains('active')) {
                    // Close the FAQ
                    faqItem.classList.remove('active');
                    targetAnswer.style.display = 'none';
                    this.setAttribute('aria-expanded', 'false');
                } else {
                    // Open the FAQ
                    faqItem.classList.add('active');
                    targetAnswer.style.display = 'block';
                    this.setAttribute('aria-expanded', 'true');
                }
            }
        });
        
        // Set initial state for expanded items
        const faqItem = toggle.closest('.faq-item');
        if (faqItem.classList.contains('active')) {
            toggle.setAttribute('aria-expanded', 'true');
        }
    });
});
</script>

<?php
get_footer();
