<?php
/**
 * Table of Contents Block Template
 *
 * @package neubird
 */

// Get block fields
$toc_title = get_field('toc_title') ?: 'Table of Contents';
$toc_heading_levels = get_field('toc_heading_levels') ?: array('h3', 'h4');
$toc_display_style = get_field('toc_display_style') ?: 'expanded';
$toc_enable_smooth_scroll = get_field('toc_enable_smooth_scroll') !== false;
$toc_enable_numbering = get_field('toc_enable_numbering') !== false;

// Generate unique ID for this TOC instance
$toc_id = 'toc-' . uniqid();
?>

<div class="table-of-contents-block" id="<?php echo $toc_id; ?>">
    <div class="toc-header">
        <h3 class="toc-title"><?php echo esc_html($toc_title); ?></h3>
        <button class="toc-toggle" aria-expanded="<?php echo $toc_display_style === 'expanded' ? 'true' : 'false'; ?>">
            <span class="toc-toggle-icon"></span>
        </button>
    </div>
    <div class="toc-content" <?php echo $toc_display_style === 'collapsed' ? 'style="display: none;"' : ''; ?>>
        <nav class="toc-nav" role="navigation" aria-label="Table of Contents">
            <ul class="toc-list" id="<?php echo $toc_id; ?>-list">
                <!-- TOC items will be generated by JavaScript -->
            </ul>
        </nav>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const tocContainer = document.getElementById('<?php echo $toc_id; ?>');
    const tocList = document.getElementById('<?php echo $toc_id; ?>-list');
    const tocToggle = tocContainer.querySelector('.toc-toggle');
    const tocContent = tocContainer.querySelector('.toc-content');
    
    // Configuration
    const config = {
        headingLevels: <?php echo json_encode($toc_heading_levels); ?>,
        enableSmoothScroll: <?php echo $toc_enable_smooth_scroll ? 'true' : 'false'; ?>,
        enableNumbering: <?php echo $toc_enable_numbering ? 'true' : 'false'; ?>
    };
    
    // Generate TOC
    function generateTOC() {
        const headings = document.querySelectorAll(config.headingLevels.join(', '));
        const tocItems = [];
        let counter = 1;
        
        headings.forEach(function(heading, index) {
            // Generate unique ID if heading doesn't have one
            if (!heading.id) {
                heading.id = 'heading-' + (index + 1);
            }
            
            const level = parseInt(heading.tagName.charAt(1));
            const text = heading.textContent.trim();
            
            tocItems.push({
                id: heading.id,
                text: text,
                level: level,
                number: config.enableNumbering ? counter++ : null
            });
        });
        
        // Build TOC HTML
        let tocHTML = '';
        let currentLevel = 0;
        
        tocItems.forEach(function(item, index) {
            const levelDiff = item.level - currentLevel;
            
            if (levelDiff > 0) {
                // Open new nested list(s)
                for (let i = 0; i < levelDiff; i++) {
                    if (currentLevel > 0 || i > 0) {
                        tocHTML += '<ul class="toc-sublist">';
                    }
                }
            } else if (levelDiff < 0) {
                // Close nested list(s)
                for (let i = 0; i < Math.abs(levelDiff); i++) {
                    tocHTML += '</ul>';
                }
            }
            
            const numberPrefix = item.number ? item.number + '. ' : '';
            tocHTML += '<li class="toc-item toc-level-' + item.level + '">';
            tocHTML += '<a href="#' + item.id + '" class="toc-link">';
            tocHTML += numberPrefix + item.text;
            tocHTML += '</a></li>';
            
            currentLevel = item.level;
        });
        
        // Close any remaining open lists
        while (currentLevel > 3) {
            tocHTML += '</ul>';
            currentLevel--;
        }
        
        tocList.innerHTML = tocHTML;
        
        // Add smooth scroll behavior
        if (config.enableSmoothScroll) {
            const tocLinks = tocList.querySelectorAll('.toc-link');
            tocLinks.forEach(function(link) {
                link.addEventListener('click', function(e) {
                    e.preventDefault();
                    const targetId = this.getAttribute('href').substring(1);
                    const targetElement = document.getElementById(targetId);
                    
                    if (targetElement) {
                        targetElement.scrollIntoView({
                            behavior: 'smooth',
                            block: 'start'
                        });
                        
                        // Update URL hash
                        history.pushState(null, null, '#' + targetId);
                    }
                });
            });
        }
    }
    
    // Toggle TOC visibility
    if (tocToggle) {
        tocToggle.addEventListener('click', function() {
            const isExpanded = this.getAttribute('aria-expanded') === 'true';
            
            if (isExpanded) {
                tocContent.style.display = 'none';
                this.setAttribute('aria-expanded', 'false');
            } else {
                tocContent.style.display = 'block';
                this.setAttribute('aria-expanded', 'true');
            }
        });
    }
    
    // Initialize TOC
    generateTOC();
    
    // Regenerate TOC if content changes (for dynamic content)
    const observer = new MutationObserver(function(mutations) {
        let shouldRegenerate = false;
        
        mutations.forEach(function(mutation) {
            if (mutation.type === 'childList') {
                const addedNodes = Array.from(mutation.addedNodes);
                const removedNodes = Array.from(mutation.removedNodes);
                
                const hasHeadingChanges = [...addedNodes, ...removedNodes].some(function(node) {
                    return node.nodeType === Node.ELEMENT_NODE && 
                           config.headingLevels.includes(node.tagName.toLowerCase());
                });
                
                if (hasHeadingChanges) {
                    shouldRegenerate = true;
                }
            }
        });
        
        if (shouldRegenerate) {
            generateTOC();
        }
    });
    
    observer.observe(document.body, {
        childList: true,
        subtree: true
    });
});
</script>